# Laboratory {.unnumbered}

In the financial year 2023/24, blood smears were the most common lab tests, making up 21% of all lab exams, which was 2,420,155 tests. This was followed by Blood glucose glycemia and Blood Full Blood Count FBC NFS test having a total of 17% lab test. It is worth noting that there were no cases of Ascariasis, Ankylostomiasis, Schistosoma, and Trichuris.

According to reported laboratory specimens, 57.6% were blood, 21.7% were Thick Blood Smears and 1.5% of the samples were from sputum.

```{r}
#| output: false

library(readxl)
library(dplyr)

laboratory_df <- read_excel("data/laboratory_data.xlsx")
laboratory_df <- laboratory_df[c(7:18),c(5:ncol(laboratory_df))] # <1>
laboratory_df <- colSums(laboratory_df[,-1])                     # <2>

```

1.  Select data for the period July 2023 to June 2024 and drop columns with text.
2.  Sum up the values for all of the columns.

| Type of Exam       | Health Cenre | District Hsopital | Medical Clinic | Referral Hospital | Private Hospital | Specialised Hospital | Total |
|--------------------|--------------|-------------------|----------------|-------------------|------------------|----------------------|-------|
| Thick Blood Smears |              |                   |                |                   |                  |                      |       |
| Stool              |              |                   |                |                   |                  |                      |       |
| Urine              |              |                   |                |                   |                  |                      |       |
| Sputum             |              |                   |                |                   |                  |                      |       |
| Blood              |              |                   |                |                   |                  |                      |       |
| Other              |              |                   |                |                   |                  |                      |       |
| Total              |              |                   |                |                   |                  |                      |       |
| \%                 |              |                   |                |                   |                  |                      |       |

: Types and Distribution of Laboratory Examinations Conducted During the FY 2023/24
